name: riverpod_scope_overlay
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-222.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: any
  hooks_riverpod: ^2.0.0-dev.9
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true